NAME_SRV = gigecam-srv

export PYLON_ROOT=/opt/pylon5

PYLON_LIBS = -L${PYLON_ROOT}/lib64 -L${PYLON_ROOT}/lib  -lpylonbase
GENICAM_LIBS = -lGenApi_gcc_v3_0_Basler_pylon_v5_0 -lGCBase_gcc_v3_0_Basler_pylon_v5_0 -lMathParser_gcc_v3_0_Basler_pylon_v5_0 -llog4cpp_gcc_v3_0_Basler_pylon_v5_0 -lLog_gcc_v3_0_Basler_pylon_v5_0 -lXmlParser_gcc_v3_0_Basler_pylon_v5_0 -lNodeMapData_gcc_v3_0_Basler_pylon_v5_0


CXXFLAGS = -I${GENICAM_ROOT}/library/CPP/include -I${PYLON_ROOT}/include -O2 -pipe -fomit-frame-pointer -DUSE_GIGE -DLIBFIT -DCONFIG_64 -DGIGECAM_RNM
LDFLAGS =   ${PYLON_LIBS} ${GENICAM_LIBS} -Wl,-E -lbufferrt -lrt -lfit -lgsl -lgslcblas -lrnm -lrnmshare

include ../Make-8.1.2.c.in
