/*----- PROTECTED REGION ID(GigeCamStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id: GigeCamStateMachine.cpp,v 1.22 2018-10-03 13:55:16 giulio Exp $";
//=============================================================================
//
// file :        GigeCamStateMachine.cpp
//
// description : C++ source for the �name� and its alowed
//               methods for commands and attributes
//
// project :     Gigabit Camera Server.
//
// $Author: giulio $
//
// $Revision: 1.22 $
// $Date: 2018-10-03 13:55:16 $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source: /home/cvsadm/cvsroot/fermi/servers/gigecam/src/GigeCamStateMachine.cpp,v $
// $Log: GigeCamStateMachine.cpp,v $
// Revision 1.22  2018-10-03 13:55:16  giulio
// Allowing set scale/offset when ccd is off, bugfixing
//
// Revision 1.21  2017-04-19 07:00:53  giulio
// Fixed feedback mode
//
// Revision 1.20  2017-03-20 12:22:22  giulio
// Added aCA2000-50gm, added support for tango based trajectory feedback
//
// Revision 1.19  2014-12-30 08:33:57  giulio
// Added Model attribute
//
// Revision 1.18  2014-08-28 07:49:45  giulio
// Added imagesum attribute and scA1400 ccd
//
// Revision 1.17  2013-08-07 08:00:26  giulio
// Added mutexes in get_data commands; moved to Tango8; changed shutdown timeouts
//
// Revision 1.16  2013-05-29 12:49:17  giulio
// Implemented hwroiparam
//
// Revision 1.15  2013-05-17 13:14:08  giulio
// Added disable trigger timeout, stream grabber configurable
//
// Revision 1.14  2013-04-11 14:29:53  giulio
// Added digital image stabilization, saved roi_threshold
//
// Revision 1.13  2013-02-08 15:12:34  giulio
// Added autoreconnect disable + avA1000 ccd
//
// Revision 1.12  2013-01-24 08:47:29  giulio
// Added binning
//
// Revision 1.11  2012-09-17 11:44:53  giulio
// Major updates (hw roi, auto gain/exposure, rnm..)
//
// Revision 1.10  2012-07-02 16:06:11  giulio
// Added saveparam command
//
// Revision 1.9  2012-01-30 12:47:01  giulio
// Added attributes for image transfer optimization
//
// Revision 1.8  2011-12-28 08:00:53  giulio
// Extended exposure timeout to its maximu value. Store all ccd parameters through SaveScale command
//
// Revision 1.7  2011/06/14 12:19:08  giulio
// Fixed GetImag16 bug
//
// Revision 1.6  2011/05/13 09:44:00  giulio
// Fixed some bugs, moved to tango7, supported Pylon 2.3.3
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================



#include <GigeCam.h>
#include <GigeCamClass.h>

/*----- PROTECTED REGION END -----*/	//	GigeCam::GigeCamStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  The server is up anc connected to a camera
//  OFF     |  the server is up but it isn't connected to any camera
//  FAULT   |  A camera doesn't respond or the external trigger is missing (if the camera is configured with external trigger).
//  ALARM   |  When communication become unreliable.


namespace GigeCam_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_HorPos_allowed()
 *	Description : Execution allowed for HorPos attribute
 */
//--------------------------------------------------------
bool GigeCam::is_HorPos_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::HorPosStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::HorPosStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_VerPos_allowed()
 *	Description : Execution allowed for VerPos attribute
 */
//--------------------------------------------------------
bool GigeCam::is_VerPos_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::VerPosStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::VerPosStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_MaxVal_allowed()
 *	Description : Execution allowed for MaxVal attribute
 */
//--------------------------------------------------------
bool GigeCam::is_MaxVal_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::MaxValStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::MaxValStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_CountMaxVal_allowed()
 *	Description : Execution allowed for CountMaxVal attribute
 */
//--------------------------------------------------------
bool GigeCam::is_CountMaxVal_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::CountMaxValStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::CountMaxValStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_HorSigma_allowed()
 *	Description : Execution allowed for HorSigma attribute
 */
//--------------------------------------------------------
bool GigeCam::is_HorSigma_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::HorSigmaStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::HorSigmaStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_VerSigma_allowed()
 *	Description : Execution allowed for VerSigma attribute
 */
//--------------------------------------------------------
bool GigeCam::is_VerSigma_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::VerSigmaStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::VerSigmaStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Area_allowed()
 *	Description : Execution allowed for Area attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Area_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::AreaStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::AreaStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_HVCovar_allowed()
 *	Description : Execution allowed for HVCovar attribute
 */
//--------------------------------------------------------
bool GigeCam::is_HVCovar_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::HVCovarStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::HVCovarStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_CameraCounter_allowed()
 *	Description : Execution allowed for CameraCounter attribute
 */
//--------------------------------------------------------
bool GigeCam::is_CameraCounter_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for CameraCounter attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::CameraCounterStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::CameraCounterStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_AcquisitionCounter_allowed()
 *	Description : Execution allowed for AcquisitionCounter attribute
 */
//--------------------------------------------------------
bool GigeCam::is_AcquisitionCounter_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::AcquisitionCounterStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::AcquisitionCounterStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Height_allowed()
 *	Description : Execution allowed for Height attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Height_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::HeightStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::HeightStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Width_allowed()
 *	Description : Execution allowed for Width attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Width_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::WidthStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::WidthStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_ProcessingTime_allowed()
 *	Description : Execution allowed for ProcessingTime attribute
 */
//--------------------------------------------------------
bool GigeCam::is_ProcessingTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::ProcessingTimeStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::ProcessingTimeStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Frequency_allowed()
 *	Description : Execution allowed for Frequency attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Frequency_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::FrequencyStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::FrequencyStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Trigger_allowed()
 *	Description : Execution allowed for Trigger attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Trigger_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Trigger attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::TriggerStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::TriggerStateAllowed_WRITE

	//	Not any excluded states for Trigger attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::TriggerStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::TriggerStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Exposure_allowed()
 *	Description : Execution allowed for Exposure attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Exposure_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Exposure attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::ExposureStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::ExposureStateAllowed_WRITE

	//	Not any excluded states for Exposure attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::ExposureStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::ExposureStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Gain_allowed()
 *	Description : Execution allowed for Gain attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Gain_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Gain attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::GainStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GainStateAllowed_WRITE

	//	Not any excluded states for Gain attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::GainStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::GainStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_RoiThreshold_allowed()
 *	Description : Execution allowed for RoiThreshold attribute
 */
//--------------------------------------------------------
bool GigeCam::is_RoiThreshold_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for RoiThreshold attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::RoiThresholdStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::RoiThresholdStateAllowed_WRITE

	//	Not any excluded states for RoiThreshold attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::RoiThresholdStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::RoiThresholdStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_AutoRoi_allowed()
 *	Description : Execution allowed for AutoRoi attribute
 */
//--------------------------------------------------------
bool GigeCam::is_AutoRoi_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for AutoRoi attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::AutoRoiStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::AutoRoiStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::AutoRoiStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::AutoRoiStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_SwRoi_allowed()
 *	Description : Execution allowed for SwRoi attribute
 */
//--------------------------------------------------------
bool GigeCam::is_SwRoi_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for SwRoi attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::SwRoiStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::SwRoiStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::SwRoiStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::SwRoiStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_HwRoi_allowed()
 *	Description : Execution allowed for HwRoi attribute
 */
//--------------------------------------------------------
bool GigeCam::is_HwRoi_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for HwRoi attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::HwRoiStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::HwRoiStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::HwRoiStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::HwRoiStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_PlotMode_allowed()
 *	Description : Execution allowed for PlotMode attribute
 */
//--------------------------------------------------------
bool GigeCam::is_PlotMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for PlotMode attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::PlotModeStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::PlotModeStateAllowed_WRITE

	//	Not any excluded states for PlotMode attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::PlotModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::PlotModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_IconSize_allowed()
 *	Description : Execution allowed for IconSize attribute
 */
//--------------------------------------------------------
bool GigeCam::is_IconSize_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for IconSize attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::IconSizeStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::IconSizeStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::IconSizeStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::IconSizeStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_LowPassOrder_allowed()
 *	Description : Execution allowed for LowPassOrder attribute
 */
//--------------------------------------------------------
bool GigeCam::is_LowPassOrder_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for LowPassOrder attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::LowPassOrderStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::LowPassOrderStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::LowPassOrderStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::LowPassOrderStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Rotation_allowed()
 *	Description : Execution allowed for Rotation attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Rotation_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Rotation attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::RotationStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::RotationStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::RotationStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::RotationStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Mirror_allowed()
 *	Description : Execution allowed for Mirror attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Mirror_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Mirror attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::MirrorStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::MirrorStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::MirrorStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::MirrorStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_ImageDepth_allowed()
 *	Description : Execution allowed for ImageDepth attribute
 */
//--------------------------------------------------------
bool GigeCam::is_ImageDepth_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ImageDepth attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::ImageDepthStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::ImageDepthStateAllowed_WRITE

	//	Not any excluded states for ImageDepth attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::ImageDepthStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::ImageDepthStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_BackgroundSubtraction_allowed()
 *	Description : Execution allowed for BackgroundSubtraction attribute
 */
//--------------------------------------------------------
bool GigeCam::is_BackgroundSubtraction_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for BackgroundSubtraction attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::BackgroundSubtractionStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::BackgroundSubtractionStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::BackgroundSubtractionStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::BackgroundSubtractionStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_EnableProcessing_allowed()
 *	Description : Execution allowed for EnableProcessing attribute
 */
//--------------------------------------------------------
bool GigeCam::is_EnableProcessing_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for EnableProcessing attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::EnableProcessingStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::EnableProcessingStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::EnableProcessingStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::EnableProcessingStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_FastProcessing_allowed()
 *	Description : Execution allowed for FastProcessing attribute
 */
//--------------------------------------------------------
bool GigeCam::is_FastProcessing_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for FastProcessing attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::FastProcessingStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::FastProcessingStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::FastProcessingStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::FastProcessingStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Saturation_allowed()
 *	Description : Execution allowed for Saturation attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Saturation_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::SaturationStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::SaturationStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_PlotLevel_allowed()
 *	Description : Execution allowed for PlotLevel attribute
 */
//--------------------------------------------------------
bool GigeCam::is_PlotLevel_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for PlotLevel attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::PlotLevelStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::PlotLevelStateAllowed_WRITE

	//	Not any excluded states for PlotLevel attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::PlotLevelStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::PlotLevelStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Pause_allowed()
 *	Description : Execution allowed for Pause attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Pause_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Pause attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::PauseStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::PauseStateAllowed_WRITE

	//	Not any excluded states for Pause attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::PauseStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::PauseStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Label_allowed()
 *	Description : Execution allowed for Label attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Label_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Label attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::LabelStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::LabelStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_HorPosRelative_allowed()
 *	Description : Execution allowed for HorPosRelative attribute
 */
//--------------------------------------------------------
bool GigeCam::is_HorPosRelative_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::HorPosRelativeStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::HorPosRelativeStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_VerPosRelative_allowed()
 *	Description : Execution allowed for VerPosRelative attribute
 */
//--------------------------------------------------------
bool GigeCam::is_VerPosRelative_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::VerPosRelativeStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::VerPosRelativeStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Phase_allowed()
 *	Description : Execution allowed for Phase attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Phase_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::PhaseStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::PhaseStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_ScaleHor_allowed()
 *	Description : Execution allowed for ScaleHor attribute
 */
//--------------------------------------------------------
bool GigeCam::is_ScaleHor_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ScaleHor attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::ScaleHorStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::ScaleHorStateAllowed_WRITE

	//	Not any excluded states for ScaleHor attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::ScaleHorStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::ScaleHorStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_ScaleVer_allowed()
 *	Description : Execution allowed for ScaleVer attribute
 */
//--------------------------------------------------------
bool GigeCam::is_ScaleVer_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ScaleVer attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::ScaleVerStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::ScaleVerStateAllowed_WRITE

	//	Not any excluded states for ScaleVer attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::ScaleVerStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::ScaleVerStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_OffsetHor_allowed()
 *	Description : Execution allowed for OffsetHor attribute
 */
//--------------------------------------------------------
bool GigeCam::is_OffsetHor_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for OffsetHor attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::OffsetHorStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::OffsetHorStateAllowed_WRITE

	//	Not any excluded states for OffsetHor attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::OffsetHorStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::OffsetHorStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_OffsetVer_allowed()
 *	Description : Execution allowed for OffsetVer attribute
 */
//--------------------------------------------------------
bool GigeCam::is_OffsetVer_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for OffsetVer attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::OffsetVerStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::OffsetVerStateAllowed_WRITE

	//	Not any excluded states for OffsetVer attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::OffsetVerStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::OffsetVerStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_PlotOffsetAxis_allowed()
 *	Description : Execution allowed for PlotOffsetAxis attribute
 */
//--------------------------------------------------------
bool GigeCam::is_PlotOffsetAxis_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for PlotOffsetAxis attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::PlotOffsetAxisStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::PlotOffsetAxisStateAllowed_WRITE

	//	Not any excluded states for PlotOffsetAxis attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::PlotOffsetAxisStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::PlotOffsetAxisStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Intensity_allowed()
 *	Description : Execution allowed for Intensity attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Intensity_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::IntensityStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::IntensityStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_SignHor_allowed()
 *	Description : Execution allowed for SignHor attribute
 */
//--------------------------------------------------------
bool GigeCam::is_SignHor_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for SignHor attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::SignHorStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::SignHorStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_SignVer_allowed()
 *	Description : Execution allowed for SignVer attribute
 */
//--------------------------------------------------------
bool GigeCam::is_SignVer_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for SignVer attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::SignVerStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::SignVerStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_ProcessMode_allowed()
 *	Description : Execution allowed for ProcessMode attribute
 */
//--------------------------------------------------------
bool GigeCam::is_ProcessMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ProcessMode attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::ProcessModeStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::ProcessModeStateAllowed_WRITE

	//	Not any excluded states for ProcessMode attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::ProcessModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::ProcessModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_DebugThread_allowed()
 *	Description : Execution allowed for DebugThread attribute
 */
//--------------------------------------------------------
bool GigeCam::is_DebugThread_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for DebugThread attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::DebugThreadStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::DebugThreadStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_BlackLevel_allowed()
 *	Description : Execution allowed for BlackLevel attribute
 */
//--------------------------------------------------------
bool GigeCam::is_BlackLevel_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for BlackLevel attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::BlackLevelStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::BlackLevelStateAllowed_WRITE

	//	Not any excluded states for BlackLevel attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::BlackLevelStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::BlackLevelStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_ImageBufferSize_allowed()
 *	Description : Execution allowed for ImageBufferSize attribute
 */
//--------------------------------------------------------
bool GigeCam::is_ImageBufferSize_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ImageBufferSize attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::ImageBufferSizeStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::ImageBufferSizeStateAllowed_WRITE

	//	Not any excluded states for ImageBufferSize attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::ImageBufferSizeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::ImageBufferSizeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_ImageAcquisitionCounter_allowed()
 *	Description : Execution allowed for ImageAcquisitionCounter attribute
 */
//--------------------------------------------------------
bool GigeCam::is_ImageAcquisitionCounter_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ImageAcquisitionCounter attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::ImageAcquisitionCounterStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::ImageAcquisitionCounterStateAllowed_WRITE

	//	Not any excluded states for ImageAcquisitionCounter attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::ImageAcquisitionCounterStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::ImageAcquisitionCounterStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_ExposureAutoEnable_allowed()
 *	Description : Execution allowed for ExposureAutoEnable attribute
 */
//--------------------------------------------------------
bool GigeCam::is_ExposureAutoEnable_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ExposureAutoEnable attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::ExposureAutoEnableStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::ExposureAutoEnableStateAllowed_WRITE

	//	Not any excluded states for ExposureAutoEnable attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::ExposureAutoEnableStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::ExposureAutoEnableStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_ExposureAutoMin_allowed()
 *	Description : Execution allowed for ExposureAutoMin attribute
 */
//--------------------------------------------------------
bool GigeCam::is_ExposureAutoMin_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ExposureAutoMin attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::ExposureAutoMinStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::ExposureAutoMinStateAllowed_WRITE

	//	Not any excluded states for ExposureAutoMin attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::ExposureAutoMinStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::ExposureAutoMinStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_ExposureAutoMax_allowed()
 *	Description : Execution allowed for ExposureAutoMax attribute
 */
//--------------------------------------------------------
bool GigeCam::is_ExposureAutoMax_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ExposureAutoMax attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::ExposureAutoMaxStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::ExposureAutoMaxStateAllowed_WRITE

	//	Not any excluded states for ExposureAutoMax attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::ExposureAutoMaxStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::ExposureAutoMaxStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GainAutoEnable_allowed()
 *	Description : Execution allowed for GainAutoEnable attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GainAutoEnable_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::GainAutoEnableStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GainAutoEnableStateAllowed_WRITE
			return false;
		}
		return true;
	}
	else

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::GainAutoEnableStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::GainAutoEnableStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GainAutoMin_allowed()
 *	Description : Execution allowed for GainAutoMin attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GainAutoMin_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for GainAutoMin attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::GainAutoMinStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GainAutoMinStateAllowed_WRITE

	//	Not any excluded states for GainAutoMin attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::GainAutoMinStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::GainAutoMinStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GainAutoMax_allowed()
 *	Description : Execution allowed for GainAutoMax attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GainAutoMax_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for GainAutoMax attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::GainAutoMaxStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GainAutoMaxStateAllowed_WRITE

	//	Not any excluded states for GainAutoMax attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::GainAutoMaxStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::GainAutoMaxStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_AutoTargetValue_allowed()
 *	Description : Execution allowed for AutoTargetValue attribute
 */
//--------------------------------------------------------
bool GigeCam::is_AutoTargetValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for AutoTargetValue attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::AutoTargetValueStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::AutoTargetValueStateAllowed_WRITE

	//	Not any excluded states for AutoTargetValue attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::AutoTargetValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::AutoTargetValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_AutoFeedbackGain_allowed()
 *	Description : Execution allowed for AutoFeedbackGain attribute
 */
//--------------------------------------------------------
bool GigeCam::is_AutoFeedbackGain_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for AutoFeedbackGain attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::AutoFeedbackGainStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::AutoFeedbackGainStateAllowed_WRITE

	//	Not any excluded states for AutoFeedbackGain attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::AutoFeedbackGainStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::AutoFeedbackGainStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_AutoFeedbackDws_allowed()
 *	Description : Execution allowed for AutoFeedbackDws attribute
 */
//--------------------------------------------------------
bool GigeCam::is_AutoFeedbackDws_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for AutoFeedbackDws attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::AutoFeedbackDwsStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::AutoFeedbackDwsStateAllowed_WRITE

	//	Not any excluded states for AutoFeedbackDws attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::AutoFeedbackDwsStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::AutoFeedbackDwsStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_AutoFeedbackTargetThres_allowed()
 *	Description : Execution allowed for AutoFeedbackTargetThres attribute
 */
//--------------------------------------------------------
bool GigeCam::is_AutoFeedbackTargetThres_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for AutoFeedbackTargetThres attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::AutoFeedbackTargetThresStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::AutoFeedbackTargetThresStateAllowed_WRITE

	//	Not any excluded states for AutoFeedbackTargetThres attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::AutoFeedbackTargetThresStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::AutoFeedbackTargetThresStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_AutoFeedbackDeadBand_allowed()
 *	Description : Execution allowed for AutoFeedbackDeadBand attribute
 */
//--------------------------------------------------------
bool GigeCam::is_AutoFeedbackDeadBand_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for AutoFeedbackDeadBand attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::AutoFeedbackDeadBandStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::AutoFeedbackDeadBandStateAllowed_WRITE

	//	Not any excluded states for AutoFeedbackDeadBand attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::AutoFeedbackDeadBandStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::AutoFeedbackDeadBandStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_FitError_allowed()
 *	Description : Execution allowed for FitError attribute
 */
//--------------------------------------------------------
bool GigeCam::is_FitError_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for FitError attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::FitErrorStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::FitErrorStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_BunchNumber_allowed()
 *	Description : Execution allowed for BunchNumber attribute
 */
//--------------------------------------------------------
bool GigeCam::is_BunchNumber_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for BunchNumber attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::BunchNumberStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::BunchNumberStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_MeanIntensityThreshold_allowed()
 *	Description : Execution allowed for MeanIntensityThreshold attribute
 */
//--------------------------------------------------------
bool GigeCam::is_MeanIntensityThreshold_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for MeanIntensityThreshold attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::MeanIntensityThresholdStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::MeanIntensityThresholdStateAllowed_WRITE

	//	Not any excluded states for MeanIntensityThreshold attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::MeanIntensityThresholdStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::MeanIntensityThresholdStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Binning_allowed()
 *	Description : Execution allowed for Binning attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Binning_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Binning attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::BinningStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::BinningStateAllowed_WRITE

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::BinningStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::BinningStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_DISEnable_allowed()
 *	Description : Execution allowed for DISEnable attribute
 */
//--------------------------------------------------------
bool GigeCam::is_DISEnable_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for DISEnable attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::DISEnableStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::DISEnableStateAllowed_WRITE

	//	Not any excluded states for DISEnable attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::DISEnableStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::DISEnableStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_DisableTriggerTimeout_allowed()
 *	Description : Execution allowed for DisableTriggerTimeout attribute
 */
//--------------------------------------------------------
bool GigeCam::is_DisableTriggerTimeout_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for DisableTriggerTimeout attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::DisableTriggerTimeoutStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::DisableTriggerTimeoutStateAllowed_WRITE

	//	Not any excluded states for DisableTriggerTimeout attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::DisableTriggerTimeoutStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::DisableTriggerTimeoutStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_ImageSumSamples_allowed()
 *	Description : Execution allowed for ImageSumSamples attribute
 */
//--------------------------------------------------------
bool GigeCam::is_ImageSumSamples_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ImageSumSamples attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::ImageSumSamplesStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::ImageSumSamplesStateAllowed_WRITE

	//	Not any excluded states for ImageSumSamples attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::ImageSumSamplesStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::ImageSumSamplesStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Model_allowed()
 *	Description : Execution allowed for Model attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Model_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Model attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::ModelStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::ModelStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_FeedbackMode_allowed()
 *	Description : Execution allowed for FeedbackMode attribute
 */
//--------------------------------------------------------
bool GigeCam::is_FeedbackMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for FeedbackMode attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::FeedbackModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::FeedbackModeStateAllowed_WRITE

	//	Not any excluded states for FeedbackMode attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::FeedbackModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::FeedbackModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_MeanIntensity_allowed()
 *	Description : Execution allowed for MeanIntensity attribute
 */
//--------------------------------------------------------
bool GigeCam::is_MeanIntensity_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for MeanIntensity attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::MeanIntensityStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::MeanIntensityStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_FeedbackError_allowed()
 *	Description : Execution allowed for FeedbackError attribute
 */
//--------------------------------------------------------
bool GigeCam::is_FeedbackError_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for FeedbackError attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::FeedbackErrorStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::FeedbackErrorStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_SearchBackgroundParam_allowed()
 *	Description : Execution allowed for SearchBackgroundParam attribute
 */
//--------------------------------------------------------
bool GigeCam::is_SearchBackgroundParam_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for SearchBackgroundParam attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::SearchBackgroundParamStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::SearchBackgroundParamStateAllowed_WRITE

	//	Not any excluded states for SearchBackgroundParam attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::SearchBackgroundParamStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::SearchBackgroundParamStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_HorProfile_allowed()
 *	Description : Execution allowed for HorProfile attribute
 */
//--------------------------------------------------------
bool GigeCam::is_HorProfile_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::HorProfileStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::HorProfileStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_VerProfile_allowed()
 *	Description : Execution allowed for VerProfile attribute
 */
//--------------------------------------------------------
bool GigeCam::is_VerProfile_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::VerProfileStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::VerProfileStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_ErrorCounters_allowed()
 *	Description : Execution allowed for ErrorCounters attribute
 */
//--------------------------------------------------------
bool GigeCam::is_ErrorCounters_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::ErrorCountersStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::ErrorCountersStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_TimeStamp_allowed()
 *	Description : Execution allowed for TimeStamp attribute
 */
//--------------------------------------------------------
bool GigeCam::is_TimeStamp_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::TimeStampStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::TimeStampStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_AutoRoiParam_allowed()
 *	Description : Execution allowed for AutoRoiParam attribute
 */
//--------------------------------------------------------
bool GigeCam::is_AutoRoiParam_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::AutoRoiParamStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::AutoRoiParamStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_RoiParam_allowed()
 *	Description : Execution allowed for RoiParam attribute
 */
//--------------------------------------------------------
bool GigeCam::is_RoiParam_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for RoiParam attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::RoiParamStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::RoiParamStateAllowed_WRITE

	//	Not any excluded states for RoiParam attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::RoiParamStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::RoiParamStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_HorFitProfile_allowed()
 *	Description : Execution allowed for HorFitProfile attribute
 */
//--------------------------------------------------------
bool GigeCam::is_HorFitProfile_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::HorFitProfileStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::HorFitProfileStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_VerFitProfile_allowed()
 *	Description : Execution allowed for VerFitProfile attribute
 */
//--------------------------------------------------------
bool GigeCam::is_VerFitProfile_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::VerFitProfileStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::VerFitProfileStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_HwRoiParam_allowed()
 *	Description : Execution allowed for HwRoiParam attribute
 */
//--------------------------------------------------------
bool GigeCam::is_HwRoiParam_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for HwRoiParam attribute in Write access.
	/*----- PROTECTED REGION ID(GigeCam::HwRoiParamStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::HwRoiParamStateAllowed_WRITE

	//	Not any excluded states for HwRoiParam attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::HwRoiParamStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::HwRoiParamStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Image8_allowed()
 *	Description : Execution allowed for Image8 attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Image8_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::Image8StateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::Image8StateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Image8Icon_allowed()
 *	Description : Execution allowed for Image8Icon attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Image8Icon_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::Image8IconStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::Image8IconStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Image16_allowed()
 *	Description : Execution allowed for Image16 attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Image16_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::Image16StateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::Image16StateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Image16Icon_allowed()
 *	Description : Execution allowed for Image16Icon attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Image16Icon_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT)
		{
		/*----- PROTECTED REGION ID(GigeCam::Image16IconStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	GigeCam::Image16IconStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Image8Counter_allowed()
 *	Description : Execution allowed for Image8Counter attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Image8Counter_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Image8Counter attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::Image8CounterStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::Image8CounterStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Image16Counter_allowed()
 *	Description : Execution allowed for Image16Counter attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Image16Counter_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Image16Counter attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::Image16CounterStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::Image16CounterStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_ImageSum_allowed()
 *	Description : Execution allowed for ImageSum attribute
 */
//--------------------------------------------------------
bool GigeCam::is_ImageSum_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for ImageSum attribute in read access.
	/*----- PROTECTED REGION ID(GigeCam::ImageSumStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GigeCam::ImageSumStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Start_allowed()
 *	Description : Execution allowed for Start attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Start_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::ON ||
		get_state()==Tango::ALARM)
	{
	/*----- PROTECTED REGION ID(GigeCam::StartStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::StartStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Stop_allowed()
 *	Description : Execution allowed for Stop attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Stop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Stop command.
	/*----- PROTECTED REGION ID(GigeCam::StopStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::StopStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_Reset_allowed()
 *	Description : Execution allowed for Reset attribute
 */
//--------------------------------------------------------
bool GigeCam::is_Reset_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Reset command.
	/*----- PROTECTED REGION ID(GigeCam::ResetStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::ResetStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_ListCamera_allowed()
 *	Description : Execution allowed for ListCamera attribute
 */
//--------------------------------------------------------
bool GigeCam::is_ListCamera_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ListCamera command.
	/*----- PROTECTED REGION ID(GigeCam::ListCameraStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::ListCameraStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_AcquireBackground_allowed()
 *	Description : Execution allowed for AcquireBackground attribute
 */
//--------------------------------------------------------
bool GigeCam::is_AcquireBackground_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::AcquireBackgroundStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::AcquireBackgroundStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetImage8_allowed()
 *	Description : Execution allowed for GetImage8 attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetImage8_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::GetImage8StateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetImage8StateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetImage16_allowed()
 *	Description : Execution allowed for GetImage16 attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetImage16_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::GetImage16StateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetImage16StateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetHorPos_allowed()
 *	Description : Execution allowed for GetHorPos attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetHorPos_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::GetHorPosStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetHorPosStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetVerPos_allowed()
 *	Description : Execution allowed for GetVerPos attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetVerPos_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::GetVerPosStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetVerPosStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetHorSigma_allowed()
 *	Description : Execution allowed for GetHorSigma attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetHorSigma_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::GetHorSigmaStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetHorSigmaStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetVerSigma_allowed()
 *	Description : Execution allowed for GetVerSigma attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetVerSigma_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::GetVerSigmaStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetVerSigmaStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetArea_allowed()
 *	Description : Execution allowed for GetArea attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetArea_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::GetAreaStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetAreaStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetAcquisitionCounter_allowed()
 *	Description : Execution allowed for GetAcquisitionCounter attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetAcquisitionCounter_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::GetAcquisitionCounterStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetAcquisitionCounterStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetSaturation_allowed()
 *	Description : Execution allowed for GetSaturation attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetSaturation_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::GetSaturationStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetSaturationStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_SetReference_allowed()
 *	Description : Execution allowed for SetReference attribute
 */
//--------------------------------------------------------
bool GigeCam::is_SetReference_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for SetReference command.
	/*----- PROTECTED REGION ID(GigeCam::SetReferenceStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::SetReferenceStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetPhase_allowed()
 *	Description : Execution allowed for GetPhase attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetPhase_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::GetPhaseStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetPhaseStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_SaveScale_allowed()
 *	Description : Execution allowed for SaveScale attribute
 */
//--------------------------------------------------------
bool GigeCam::is_SaveScale_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::SaveScaleStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::SaveScaleStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_RestoreScale_allowed()
 *	Description : Execution allowed for RestoreScale attribute
 */
//--------------------------------------------------------
bool GigeCam::is_RestoreScale_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::RestoreScaleStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::RestoreScaleStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_SetMeasurePoint_allowed()
 *	Description : Execution allowed for SetMeasurePoint attribute
 */
//--------------------------------------------------------
bool GigeCam::is_SetMeasurePoint_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::SetMeasurePointStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::SetMeasurePointStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_ClearMeasurePoints_allowed()
 *	Description : Execution allowed for ClearMeasurePoints attribute
 */
//--------------------------------------------------------
bool GigeCam::is_ClearMeasurePoints_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::ClearMeasurePointsStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::ClearMeasurePointsStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetIntensity_allowed()
 *	Description : Execution allowed for GetIntensity attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetIntensity_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::GetIntensityStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetIntensityStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetHorProfile_allowed()
 *	Description : Execution allowed for GetHorProfile attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetHorProfile_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::GetHorProfileStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetHorProfileStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetVerProfile_allowed()
 *	Description : Execution allowed for GetVerProfile attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetVerProfile_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::GetVerProfileStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetVerProfileStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetHorFitProfile_allowed()
 *	Description : Execution allowed for GetHorFitProfile attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetHorFitProfile_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::GetHorFitProfileStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetHorFitProfileStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetVerFitProfile_allowed()
 *	Description : Execution allowed for GetVerFitProfile attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetVerFitProfile_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::GetVerFitProfileStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetVerFitProfileStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_SaveParam_allowed()
 *	Description : Execution allowed for SaveParam attribute
 */
//--------------------------------------------------------
bool GigeCam::is_SaveParam_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for SaveParam command.
	/*----- PROTECTED REGION ID(GigeCam::SaveParamStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::SaveParamStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_ClearReference_allowed()
 *	Description : Execution allowed for ClearReference attribute
 */
//--------------------------------------------------------
bool GigeCam::is_ClearReference_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ClearReference command.
	/*----- PROTECTED REGION ID(GigeCam::ClearReferenceStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::ClearReferenceStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_ExposureAutoOnce_allowed()
 *	Description : Execution allowed for ExposureAutoOnce attribute
 */
//--------------------------------------------------------
bool GigeCam::is_ExposureAutoOnce_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::ExposureAutoOnceStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::ExposureAutoOnceStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GainAutoOnce_allowed()
 *	Description : Execution allowed for GainAutoOnce attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GainAutoOnce_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(GigeCam::GainAutoOnceStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GainAutoOnceStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetFitError_allowed()
 *	Description : Execution allowed for GetFitError attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetFitError_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for GetFitError command.
	/*----- PROTECTED REGION ID(GigeCam::GetFitErrorStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetFitErrorStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetBunchNumber_allowed()
 *	Description : Execution allowed for GetBunchNumber attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetBunchNumber_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for GetBunchNumber command.
	/*----- PROTECTED REGION ID(GigeCam::GetBunchNumberStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetBunchNumberStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetMaxVal_allowed()
 *	Description : Execution allowed for GetMaxVal attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetMaxVal_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for GetMaxVal command.
	/*----- PROTECTED REGION ID(GigeCam::GetMaxValStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetMaxValStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetGain_allowed()
 *	Description : Execution allowed for GetGain attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetGain_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for GetGain command.
	/*----- PROTECTED REGION ID(GigeCam::GetGainStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetGainStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GigeCam::is_GetExposure_allowed()
 *	Description : Execution allowed for GetExposure attribute
 */
//--------------------------------------------------------
bool GigeCam::is_GetExposure_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for GetExposure command.
	/*----- PROTECTED REGION ID(GigeCam::GetExposureStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	GigeCam::GetExposureStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(GigeCam::GigeCamStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	GigeCam::GigeCamStateAllowed.AdditionalMethods

}	//	End of namespace
